# Generated by Django 3.0.6 on 2020-08-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_auto_20200520_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='book',
            new_name='tournament',
        ),
    ]
