# Generated by Django 3.0.6 on 2020-08-31 13:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_auto_20200831_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Organisation',
        ),
        migrations.RemoveIndex(
            model_name='organisation',
            name='firstapp_bo_name_27ec38_gin',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tournament',
            new_name='organisation',
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='firstapp_or_name_59ce87_gin'),
        ),
    ]
