# Generated by Django 3.0.6 on 2020-08-31 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0024_auto_20200831_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='Number',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Player',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='genre',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='author',
            new_name='number',
        ),
    ]
