# Generated by Django 3.0.6 on 2020-08-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_auto_20200831_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='organisation',
            new_name='org',
        ),
    ]
